### ISSUE TITLE
Xmind的源文件可以上传下吗

### ISSUE THREAD

**Issue by Doracool** [MisterBooo/ReadyForBAT#5]
你好 我想在Xmind中查看这些图片，但是上边都是png的类型

**Comment by MisterBooo** [comment]
<img width="812" alt="qq20181222-161157 2x" src="https://user-images.githubusercontent.com/15308811/50372181-6b385300-0604-11e9-9286-48bc7252ec2e.png">
这个就是源文件，使用 mindNode 就可以打开编辑
